[build]
  base = ""
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "8"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
